### ISSUE TITLE
UnboundLocalError: local variable 't' referenced before assignment

### ISSUE THREAD

**Issue by seanauriti** [OWASP/BLT#394]
View details in Rollbar: [https://rollbar.com/bugheist/Bugheist/items/66/](https://rollbar.com/bugheist/Bugheist/items/66/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/website/views.py", line 111, in domain_check
    url_parsed = domain_url[t:k]
UnboundLocalError: local variable 't' referenced before assignment
```

**Comment by goyal-sidd** [comment]
Fixed in #397
