### ISSUE TITLE
DoesNotExist: Domain matching query does not exist.

### ISSUE THREAD

**Issue by seanauriti** [OWASP/BLT#405]
View details in Rollbar: [https://rollbar.com/bugheist/Bugheist/items/67/](https://rollbar.com/bugheist/Bugheist/items/67/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 155, in get
    context = self.get_context_data(**kwargs)
  File "/app/website/views.py", line 383, in get_context_data
    context['domain'] = Domain.objects.get(name=self.kwargs['slug'])
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Domain matching query does not exist.
```

**Comment by goyal-sidd** [comment]
Fixed in #397
