### ISSUE TITLE
ValueError: Missing staticfiles manifest entry for 'img/browser-logos/mobile safari/mobile safari_64x64.png'

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT#447]
View details in Rollbar: [https://rollbar.com/bugheist/Bugheist/items/70/](https://rollbar.com/bugheist/Bugheist/items/70/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/defaulttags.py", line 529, in render
    return self.nodelist.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'img/browser-logos/mobile safari/mobile safari_64x64.png'
```

**Comment by fredfalcon** [comment]
I don't see this happening anymore
