### ISSUE TITLE
UnboundLocalError: local variable 'context' referenced before assignment

### ISSUE THREAD

**Issue by seanauriti** [OWASP/BLT#477]
View details in Rollbar: [https://rollbar.com/bugheist/Bugheist/items/73/](https://rollbar.com/bugheist/Bugheist/items/73/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/website/views.py", line 541, in search
    return render(request, template, context)
UnboundLocalError: local variable 'context' referenced before assignment
```

**Comment by souravbadami** [comment]
Fixed via #499.
