### ISSUE TITLE
Server Error : BLT API

### ISSUE THREAD

**Issue by Tikam02** [OWASP/BLT#599]
![screenshot from 2018-03-12 22-07-49](https://user-images.githubusercontent.com/10548085/37296771-f5aef4b0-2641-11e8-811a-4f9cfc8cad23.png)
![bltn](https://user-images.githubusercontent.com/10548085/37296774-f6927abe-2641-11e8-8566-21b421f7e623.png)

(py2) root@hal:~/Projects/py2/BLT# python2 manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
March 12, 2018 - 16:39:33
Django version 1.11.11, using settings 'bugheist.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Projects/py2/BLT/website/views.py", line 80, in index
    return render(request, template, context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 65, in render
    for p in providers.registry.get_list(request)])
  File "/root/Projects/py2/local/lib/python2.7/site-packages/allauth/socialaccount/providers/facebook/provider.py", line 167, in media_js
    request=request)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'facebook/js/fbconnect.js'
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/whitenoise/base.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/views/defaults.py", line 74, in server_error
    return http.HttpResponseServerError(template.render())
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/root/Projects/py2/local/lib/python2.7/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 63, in render
    request = template_context_value(context, 'request')
  File "/root/Projects/py2/local/lib/python2.7/site-packages/allauth/compat.py", line 25, in template_context_value
    value = getattr(context, key)
AttributeError: 'Context' object has no attribute 'request'

**Comment by souravbadami** [comment]
Being discussed on #598.
