### ISSUE TITLE
Authentication bug.

### ISSUE THREAD

**Issue by souravbadami** [OWASP/BLT#611]
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/whitenoise/base.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 146, in __call__
    response = self.get_response(request)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/core/handlers/base.py", line 81, in get_response
    response = self._middleware_chain(request)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/core/handlers/exception.py", line 126, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/views/defaults.py", line 75, in server_error
    return HttpResponseServerError(template.render())
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 56, in render
    request = context['request']
  File "/Users/sourav/.local/share/virtualenvs/BLT-1QW7n6SR/lib/python3.6/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'request'
```

**Reproduce**: Visit https://www.bugheist.com/accounts/login/ and try to login or signup.

**Comment by souravbadami** [comment]
@seanauriti @srahulbadami -- Can you confirm this ?

**Comment by fredfalcon** [comment]
fixed, updated database
